name: Terraform
on: #[push]
  workflow_run:
    workflows: ["App"]
    branches: [master]
    types:
      - completed
jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: terraform fmt -check -recursive -diff

  validate:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./

  mock-plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init
        working-directory: ./
      - name: Terraform Plan (Mock)
        run: terraform plan -out tfplan.binary
        working-directory: ./

  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run infracost diff
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      - name: Generate Infracost JSON
        run: infracost breakdown . --format json --out-file /tmp/infracost.json
        working-directory: ./


